<a href="https://colab.research.google.com/github/pabloecheg/Business-Intelligence/blob/main/Analisis_de_Riesgos_y_Simulacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Una empresa en el oeste de los Estados Unidos fabrica y distribuye bolsos de
mujer a tiendas minoristas en todo el país.
Para fabricar un bolso, la empresa por lo general incurre en un costo variable
de 40 por bolso, pero los costos reales en el pasado han oscilado entre 35
y 46 por bolso.
El costo fijo total suele ser de 43,000, pero puede variar entre 31,000 y
52,000.
El precio minorista de cada bolso es de 65. Según una pequeña cantidad de
datos de ventas disponibles, la demanda ha fluctuado entre 2500 y 5000
bolsos por trimestre, pero en la mayoría de los trimestres la demanda ha sido
de unos 3500 bolsos.
Realice un análisis de riesgo para evaluar la rentabilidad trimestral de la
empresa.


$$Ganancia = (Precio\_unitario - Costos\_variable) * Demanda - Costos\_fijo $$

In [ ]:
def ganancia(p, cv, d, cf): #Definicion de la funcion ganancia y sus parametros de entrada
  g = (p - cv) * d - cf #Operacion de la Ganancia
  return g #Salida de la función declaradda

In [ ]:
#Definimos los escenarios
pesimista = ganancia(65, 46, 2500, 52000)
optimista = ganancia(65, 40, 3500, 43000)
probable = ganancia(65, 35, 5000, 31000)

In [ ]:
import pandas as pd

df = pd.DataFrame([pesimista, optimista, probable], columns=['Ganancia'], index=['Pesimista', 'Optimista', 'Probable'])
df

Ganancia
Pesimista     -4500
Optimista     44500
Probable     119000

## Ejemplo

Una empresa estima que el 30% de sus clientes reaccionarían positivamente
a sus nuevas funciones web.
Aquí, demostramos cómo generar observaciones aleatorias que representen
la cantidad de clientes que reaccionen positivamente a las nuevas funciones
web de la empresa en un grupo de 10 clientes seleccionados al azar.
Simule observaciones aleatorias basadas en 100 grupos de 10 clientes.


In [ ]:
import numpy as np

np.random.seed(1) #Inicializamos la semilla para la generacion pseudoaleatoria
salida = np.random.binomial(n = 10, p = 0.3, size = 100) #Generamos las observaciones con el numero de trials, p la prob de exito y size la cantidad de observaciones a generar
print(f"Promedio: {np.mean(salida)}")
print(f"Desviación estándar: {np.std(salida)}")

Promedio: 2.93
Desviación estándar: 1.5050249167372611


Para este caso, se trabaja con una distribucion Binomial, debido a que es un proceso de Bernoulli, esto es:
$$n = 10$$
$$p = 0.3$$
$$\bar{X} = np$$
$$s = \sqrt{np(1-np)}$$

## Ejemplo

Un proveedor de suministros médicos examina la demanda semanal de ventiladores respiratorios en los hospitales para los últimas 90 semanas.

|Demanda de Ventiladores|Frecuencia|
|---|---|
|100|20|
|200|25|
|300|35|
|400|10|

Estimar la demanda de ventiladores para 100 semanas, segun la distribucion empirica de la tabla.

In [ ]:
#Establecemos los datos de entrada
unidades = np.array([100,200,300,400])
semanas = np.array([20,25,35,10])

In [ ]:
#Calculamos la frecuencia relativa
frecuencia_relativa = semanas / np.sum(semanas)
#Visualizamos
frecuencia_relativa

array([0.22222222, 0.27777778, 0.38888889, 0.11111111])

In [ ]:
#Calculamos la probabilidad acumulativa
probabilidad_acumul = np.cumsum(frecuencia_relativa)
#Visualizamos
probabilidad_acumul

array([0.22222222, 0.5       , 0.88888889, 1.        ])

In [ ]:
#Fijamos la semilla
np.random.seed(1)
#Generamos los numeros aleatorios
aleatorios = np.random.uniform(low = 0, high = 1, size = 100)

In [ ]:
#A la probabilidad acumulada, le agregamos un cero al inicio para generar los intervalos de la distribucion empirica
probabilidad_acumul_bins = np.insert(probabilidad_acumul, 0, 0)
#Visualizamos
probabilidad_acumul_bins

array([0.        , 0.22222222, 0.5       , 0.88888889, 1.        ])

In [ ]:
#Calculamos la demanda de ventiladores para la distribucion empirica
demanda = pd.cut(aleatorios, bins = probabilidad_acumul_bins, labels = unidades)

In [ ]:
#Calculamos el promedio y la desviacion estandar como medidas de resumen de la demanda
print(f"Promedio: {np.mean(demanda)}")
print(f"Desviación estándar: {np.std(demanda, ddof = 1)}")

Promedio: 235.0
Desviación estándar: 99.87365756167877


## Ejemplo

Un fabricante de bolsos determina que su peor, mejor y más
probable ganancia (o pérdida) es de −4,500, 119,000 y 44,500,
respectivamente. Debido a que no tenemos datos históricos detallados o información adicional para hacer suposiciones sobre cualquier distribución
teórica, usamos una distribución de probabilidad triangular para
evaluar la incertidumbre de la ganancia del fabricante. Genere 100 observaciones aleatorias basadas en una distribución de
probabilidad triangular.


In [ ]:
#Planteamos los tres escenarios
peor = -4500
mejor = 119000
probable = 44500

#Calculamos el umbral
umbral = (probable - peor) / (mejor - peor)
umbral

0.3967611336032389

In [ ]:
#Generamos el numero aleatorio X
np.random.seed(1)
x = np.random.uniform(low = 0, high = 1, size = 100)

#Calculamos la ganancia para los casos de la distribucion triangular
ganancia_inferior = peor + np.sqrt((mejor - peor) * (probable - peor) * x)
ganancia_superior = mejor - np.sqrt((mejor - peor) * (probable - peor) * (1 - x))

In [ ]:
#Calculamos la ganancia
ganancia = np.where(x < umbral, ganancia_inferior, ganancia_superior)

#Calculamos las medias de resumen
print(f"Promedio: {np.mean(ganancia)}")
print(f"Desviación estándar: {np.std(ganancia, ddof = 1)}")

Promedio: 57535.8379461368
Desviación estándar: 28836.682434555023


## Parcial

### Ejercicio 1

La vida útil promedio de la batería de un teléfono inteligente es de 2.3 años y sigue una distribución exponencial. El fabricante de la batería quiere ofrecer una garantía para que sus clientes reciban un reemplazo gratuito si la batería falla durante el primer año. Cada batería genera una ganancia de 10.85 y el costo de reemplazo es de 6.35. Utilice una semilla de 1, y desarrolle una simulación de Monte Carlo para la vida útil de 100 baterías.   

    
Cuál es el costo total esperado de este programa de garantía?

No olvides adjuntar el archivo con el código que respalde tu respuesta.

In [ ]:
import numpy as np
import pandas as pd
import random

#Insertamos los parametros
vida_util = 2.3
ganancia = 10.85
costo_reemplazo = 6.35
tasa_error = 1 / vida_util
n_simulaciones = 100

#Fijamos la semilla
np.random.seed(1)

#Generamos los numeros aleatorios de la vida util de las baterias
vida_bateria = np.random.exponential(scale = vida_util, size = n_simulaciones)

#Contar cuantas baterias fallan en el primer año
garantia = np.sum(vida_bateria < 1)

#Calculamos el costo total
costo_total = costo_reemplazo * garantia

#Calculamos si el programa da utilidad
utilidad = (n_simulaciones * ganancia) -(garantia * costo_reemplazo)

#Visualizamos los resultados
print(f"El costo total del programa de garantía es {costo_total}")
print(f"La utilidad/perdida del programa de garantía es {utilidad}")


El costo total del programa de garantía es 241.29999999999998
La utilidad/perdida del programa de garantía es 843.7
